from __future__ import annotations

import hashlib
import json
import sys
import unittest
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import check_implementation_traceability as traceability  # noqa: E402


class ImplementationTraceabilityTests(unittest.TestCase):
    def test_every_controlling_clause_is_hash_bound_and_traced(self) -> None:
        clauses, parse_errors = traceability.parse_clauses()
        self.assertEqual([], parse_errors)
        trace = traceability.load(traceability.TRACE)
        rows = {row["id"]: row for row in trace["requirements"]}
        self.assertEqual(63, len(clauses))
        self.assertEqual(set(clauses), set(rows))
        self.assertEqual(
            hashlib.sha256(traceability.SOURCE.read_bytes()).hexdigest(),
            trace["source_manifest"]["document_sha256"],
        )
        for identifier, clause in clauses.items():
            row = rows[identifier]
            self.assertEqual(clause["text"], row["requirement"])
            self.assertEqual(clause["sha256"], row["source_clause"]["sha256"])
            self.assertEqual(
                row["status"], row["release_disposition"]["status"]
            )

    def test_prefreeze_terminal_statuses_do_not_claim_external_passage(
        self,
    ) -> None:
        trace = traceability.load(traceability.TRACE)
        counts = Counter(row["status"] for row in trace["requirements"])
        self.assertEqual(
            Counter(
                {
                    "verified": 51,
                    "blocked": 9,
                    "superseded": 2,
                    "deferred": 1,
                }
            ),
            counts,
        )
        self.assertNotIn("passed", counts)
        self.assertEqual("blocked", next(
            row["status"] for row in trace["requirements"] if row["id"] == "D-01"
        ))
        self.assertEqual("deferred", next(
            row["status"] for row in trace["requirements"] if row["id"] == "D-06"
        ))
        externally_closable = {
            "P06-03",
            "P08-06",
            "P09-05",
            "P10-02",
            "P10-03",
            "P10-04",
            "D-01",
            "D-05",
            "D-07",
        }
        by_id = {row["id"]: row for row in trace["requirements"]}
        self.assertEqual(
            externally_closable,
            {
                identifier
                for identifier, row in by_id.items()
                if row["status"] == "blocked"
            },
        )
        for identifier in externally_closable:
            row = by_id[identifier]
            self.assertIn(
                "externally closable only after exact freeze",
                row["release_disposition"]["reason"],
            )
            self.assertIn(
                "release-assurance/gap-register.json",
                row["validation_evidence"],
            )

    def test_gap_counts_and_status_report_are_synchronized(self) -> None:
        self.assertEqual([], traceability.validate_gap_register())
        trace = traceability.load(traceability.TRACE)
        counts = Counter(row["status"] for row in trace["requirements"])
        self.assertEqual([], traceability.validate_status_markdown(counts))
        gaps = json.loads(traceability.GAPS.read_text(encoding="utf-8"))
        self.assertEqual(28, gaps["source_research_gap_register"]["records"])
        actual = Counter(row["status"] for row in gaps["gaps"])
        self.assertEqual(
            {**dict(sorted(actual.items())), "total": len(gaps["gaps"])},
            gaps["counts"],
        )

    def test_evaluation_evidence_is_bound_to_selected_current_run(self) -> None:
        self.assertEqual(
            [],
            traceability.validate_current_evaluation_references(),
        )
        gaps = json.loads(traceability.GAPS.read_text(encoding="utf-8"))
        self.assertEqual(
            {
                "blocked": 5,
                "deferred": 3,
                "open": 2,
                "resolved": 16,
                "total": 26,
            },
            gaps["counts"],
        )

    def test_yaml_ld_provenance_claim_distinguishes_authored_and_generated(
        self,
    ) -> None:
        trace = traceability.load(traceability.TRACE)
        row = next(
            requirement
            for requirement in trace["requirements"]
            if requirement["id"] == "P02-01"
        )
        reason = row["release_disposition"]["reason"]
        self.assertIn(
            "whole-law/okf-bundle.yamlld is the authored semantic source",
            reason,
        )
        self.assertIn(
            "root Legislation bundle/okf-bundle.yamlld is instead "
            "code-generated by scripts/build_legislation_okf.py",
            reason,
        )
        self.assertEqual("verified", row["status"])

    def test_complete_phase_one_validation_is_clean(self) -> None:
        self.assertEqual([], traceability.validate())


if __name__ == "__main__":
    unittest.main()
